//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Codeable.Foundation.Common;
using Stencil.Common;
using Stencil.Domain;
using Stencil.Primary.Business.Index;
using Stencil.Primary.Health;
using sdk = Stencil.SDK.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using Codeable.Foundation.Core;

namespace Stencil.Primary.Synchronization.Implementation
{
    public partial class ProductVersionPlatformSynchronizer : SynchronizerBase<Guid>, IProductVersionPlatformSynchronizer
    {
        public ProductVersionPlatformSynchronizer(IFoundation foundation)
            : base(foundation, "ProductVersionPlatformSynchronizer")
        {

        }

        public override int Priority
        {
            get
            {
                return 60;
            }
        }

        public override void PerformSynchronizationForItem(Guid primaryKey)
        {
            base.ExecuteMethod("PerformSynchronizationForItem", delegate ()
            {
                ProductVersionPlatform domainModel = this.API.Direct.ProductVersionPlatforms.GetById(primaryKey);
                if (domainModel != null)
                {
                    Action<Guid, bool, DateTime, string> synchronizationUpdateMethod = this.API.Direct.ProductVersionPlatforms.SynchronizationUpdate;
                    if(this.API.Integration.SettingsResolver.IsHydrate())
                    {
                        synchronizationUpdateMethod = this.API.Direct.ProductVersionPlatforms.SynchronizationHydrateUpdate;
                    }
                    DateTime syncDate = DateTime.UtcNow;
                    if (domainModel.sync_invalid_utc.HasValue)
                    {
                        syncDate = domainModel.sync_invalid_utc.Value;
                    }
                    try
                    {
                        sdk.ProductVersionPlatform sdkModel = domainModel.ToSDKModel();
                        
                        this.HydrateSDKModelComputed(domainModel, sdkModel);
                        this.HydrateSDKModel(domainModel, sdkModel);

                        if (domainModel.deleted_utc.HasValue)
                        {
                            this.API.Index.ProductVersionPlatforms.DeleteDocument(sdkModel);
                            synchronizationUpdateMethod(domainModel.product_version_platform_id, true, syncDate, null);
                        }
                        else
                        {
                            IndexResult result = this.API.Index.ProductVersionPlatforms.UpdateDocument(sdkModel);
                            if (result.success)
                            {
                                synchronizationUpdateMethod(domainModel.product_version_platform_id, true, syncDate, result.ToString());
                            }
                            else
                            {
                                throw new Exception(result.ToString());
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        this.IFoundation.LogError(ex, "PerformSynchronizationForItem");
                        HealthReporter.Current.UpdateMetric(HealthTrackType.Each, string.Format(HealthReporter.INDEXER_ERROR_SYNC, this.EntityName), 0, 1);
                        synchronizationUpdateMethod(primaryKey, false, syncDate, CoreUtility.FormatException(ex));
                    }
                }
            });
        }

        public override int PerformSynchronization(string requestedAgentName)
        {
            return base.ExecuteFunction("PerformSynchronization", delegate ()
            {
                string agentName = requestedAgentName;
                if(string.IsNullOrEmpty(agentName))
                {
                    agentName = this.AgentName;
                }
                List<Guid?> invalidItems = new List<Guid?>();
                if(this.API.Integration.SettingsResolver.IsHydrate())
                {
                    invalidItems = this.API.Direct.ProductVersionPlatforms.SynchronizationHydrateGetInvalid(CommonAssumptions.INDEX_RETRY_THRESHOLD_SECONDS, agentName);
                }
                else
                {
                    invalidItems = this.API.Direct.ProductVersionPlatforms.SynchronizationGetInvalid(CommonAssumptions.INDEX_RETRY_THRESHOLD_SECONDS, agentName);
                }
                foreach (Guid? item in invalidItems)
                {
                    this.PerformSynchronizationForItem(item.GetValueOrDefault());
                }
                return invalidItems.Count;
            });
        }
        
        /// <summary>
        /// Computed and Calculated Aggs, Typically Generated
        /// </summary>
        protected void HydrateSDKModelComputed(ProductVersionPlatform domainModel, sdk.ProductVersionPlatform sdkModel)
        {
            
            sdk.ProductVersion referenceProductVersion = this.API.Index.ProductVersions.GetById(sdkModel.product_version_id);
            if(referenceProductVersion != null)
            {
                sdkModel.product_version = referenceProductVersion.version;
            }
            else
            {
                ProductVersion referenceDomainProductVersion = this.API.Direct.ProductVersions.GetById(sdkModel.product_version_id);
                if(referenceDomainProductVersion != null)
                {
                    sdkModel.product_version = referenceDomainProductVersion.version;
                }
            }
            
            sdk.Platform referencePlatform = this.API.Index.Platforms.GetById(sdkModel.platform_id);
            if(referencePlatform != null)
            {
                sdkModel.platform_name = referencePlatform.platform_name;
            }
            else
            {
                Platform referenceDomainPlatform = this.API.Direct.Platforms.GetById(sdkModel.platform_id);
                if(referenceDomainPlatform != null)
                {
                    sdkModel.platform_name = referenceDomainPlatform.platform_name;
                }
            }
            
        }
        partial void HydrateSDKModel(ProductVersionPlatform domainModel, sdk.ProductVersionPlatform sdkModel);
    }
}

