//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if WINDOWS_PHONE_APP
using RestSharp.Portable;
#else
using RestSharp;
#endif
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Stencil.SDK.Models;

namespace Stencil.SDK.Endpoints
{
    public partial class AffectedProductEndpoint : EndpointBase
    {
        public AffectedProductEndpoint(StencilSDK api)
            : base(api)
        {

        }
        
        public Task<ItemResult<AffectedProduct>> GetAffectedProductAsync(Guid affected_product_id)
        {
            var request = new RestRequest(Method.GET);
            request.Resource = "affectedproducts/{affected_product_id}";
            request.AddUrlSegment("affected_product_id", affected_product_id.ToString());
            
            return this.Sdk.ExecuteAsync<ItemResult<AffectedProduct>>(request);
        }
        
        
        public Task<ListResult<AffectedProduct>> GetAffectedProductByTicketIDAsync(Guid ticket_id, int skip = 0, int take = 10, string order_by = "", bool descending = false)
        {
            var request = new RestRequest(Method.GET);
            request.Resource = "affectedproducts/by_ticketid/{ticket_id}";
            request.AddUrlSegment("ticket_id", ticket_id.ToString());
            request.AddParameter("skip", skip);
            request.AddParameter("take", take);
            request.AddParameter("order_by", order_by);
            request.AddParameter("descending", descending);
            
            return this.Sdk.ExecuteAsync<ListResult<AffectedProduct>>(request);
        }
        
        public Task<ListResult<AffectedProduct>> GetAffectedProductByProductIDAsync(Guid product_id, int skip = 0, int take = 10, string order_by = "", bool descending = false)
        {
            var request = new RestRequest(Method.GET);
            request.Resource = "affectedproducts/by_productid/{product_id}";
            request.AddUrlSegment("product_id", product_id.ToString());
            request.AddParameter("skip", skip);
            request.AddParameter("take", take);
            request.AddParameter("order_by", order_by);
            request.AddParameter("descending", descending);
            
            return this.Sdk.ExecuteAsync<ListResult<AffectedProduct>>(request);
        }
        

        public Task<ItemResult<AffectedProduct>> CreateAffectedProductAsync(AffectedProduct affectedproduct)
        {
            var request = new RestRequest(Method.POST);
            request.Resource = "affectedproducts";
            request.AddJsonBody(affectedproduct);
            return this.Sdk.ExecuteAsync<ItemResult<AffectedProduct>>(request);
        }

        public Task<ItemResult<AffectedProduct>> UpdateAffectedProductAsync(Guid affected_product_id, AffectedProduct affectedproduct)
        {
            var request = new RestRequest(Method.PUT);
            request.Resource = "affectedproducts/{affected_product_id}";
            request.AddUrlSegment("affected_product_id", affected_product_id.ToString());
            request.AddJsonBody(affectedproduct);
            return this.Sdk.ExecuteAsync<ItemResult<AffectedProduct>>(request);
        }

        

        public Task<ActionResult> DeleteAffectedProductAsync(Guid affected_product_id)
        {
            var request = new RestRequest(Method.DELETE);
            request.Resource = "affectedproducts/{affected_product_id}";
            request.AddUrlSegment("affected_product_id", affected_product_id.ToString());
            return this.Sdk.ExecuteAsync<ActionResult>(request);
        }
    }
}
