//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if WINDOWS_PHONE_APP
using RestSharp.Portable;
#else
using RestSharp;
#endif
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Stencil.SDK.Models;

namespace Stencil.SDK.Endpoints
{
    public partial class PlatformEndpoint : EndpointBase
    {
        public PlatformEndpoint(StencilSDK api)
            : base(api)
        {

        }
        
        public Task<ItemResult<Platform>> GetPlatformAsync(Guid platform_id)
        {
            var request = new RestRequest(Method.GET);
            request.Resource = "platforms/{platform_id}";
            request.AddUrlSegment("platform_id", platform_id.ToString());
            
            return this.Sdk.ExecuteAsync<ItemResult<Platform>>(request);
        }
        
        public Task<ListResult<Platform>> Find(int skip = 0, int take = 10, string keyword = "", string order_by = "", bool descending = false)
        {
            var request = new RestRequest(Method.GET);
            request.Resource = "platforms";
            request.AddParameter("skip", skip);
            request.AddParameter("take", take);
            request.AddParameter("order_by", order_by);
            request.AddParameter("descending", descending);
            request.AddParameter("keyword", keyword);
            
            
            return this.Sdk.ExecuteAsync<ListResult<Platform>>(request);
        }

        public Task<ItemResult<Platform>> CreatePlatformAsync(Platform platform)
        {
            var request = new RestRequest(Method.POST);
            request.Resource = "platforms";
            request.AddJsonBody(platform);
            return this.Sdk.ExecuteAsync<ItemResult<Platform>>(request);
        }

        public Task<ItemResult<Platform>> UpdatePlatformAsync(Guid platform_id, Platform platform)
        {
            var request = new RestRequest(Method.PUT);
            request.Resource = "platforms/{platform_id}";
            request.AddUrlSegment("platform_id", platform_id.ToString());
            request.AddJsonBody(platform);
            return this.Sdk.ExecuteAsync<ItemResult<Platform>>(request);
        }

        

        public Task<ActionResult> DeletePlatformAsync(Guid platform_id)
        {
            var request = new RestRequest(Method.DELETE);
            request.Resource = "platforms/{platform_id}";
            request.AddUrlSegment("platform_id", platform_id.ToString());
            return this.Sdk.ExecuteAsync<ActionResult>(request);
        }
    }
}
