//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Stencil.SDK.Models
{
    public partial class AffectedProduct : SDKModel
    {	
        public AffectedProduct()
        {
				
        }
    
        public virtual Guid affected_product_id { get; set; }
        public virtual Guid ticket_id { get; set; }
        public virtual Guid product_id { get; set; }
        
	}
}

