//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;

namespace Stencil.SDK.Models
{
    public enum AssetType
    {
        Image = 0,
        Video = 1
    }
}
