//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;

namespace Stencil.SDK.Models
{
    public enum Bitness
    {
        Eight = 8,
        Twelve = 12,
        Sixteen = 16,
        ThirtyTwo = 32,
        ThirtySix = 36,
        SixtyFour = 64
    }
}
