//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Stencil.SDK.Models
{
    public partial class Commit : SDKModel
    {	
        public Commit()
        {
				
        }
    
        public virtual Guid commit_id { get; set; }
        public virtual string commit_ref { get; set; }
        public virtual string commit_author_name { get; set; }
        public virtual string commit_author_email { get; set; }
        public virtual DateTime? commit_message_decoded_utc { get; set; }
        public virtual string commit_message { get; set; }
        
	}
}

