//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Stencil.SDK.Models
{
    public partial class GlobalSetting : SDKModel
    {	
        public GlobalSetting()
        {
				
        }
    
        public virtual Guid global_setting_id { get; set; }
        public virtual string name { get; set; }
        public virtual string value { get; set; }
        
	}
}

