//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Stencil.SDK.Models
{
    public partial class Platform : SDKModel
    {	
        public Platform()
        {
				
        }
    
        public virtual Guid platform_id { get; set; }
        public virtual string platform_name { get; set; }
        public virtual Bitness bitness { get; set; }
        
	}
}

