//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Stencil.SDK.Models
{
    public partial class ProductVersionPlatform : SDKModel
    {	
        public ProductVersionPlatform()
        {
				
        }
    
        public virtual Guid product_version_platform_id { get; set; }
        public virtual Guid product_version_id { get; set; }
        public virtual Guid platform_id { get; set; }
        
        //<IndexOnly>
        
        public string product_version { get; set; }
        public string platform_name { get; set; }
        
        //</IndexOnly>
	}
}

