//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Stencil.SDK.Models
{
    public partial class Product : SDKModel
    {	
        public Product()
        {
				
        }
    
        public virtual Guid product_id { get; set; }
        public virtual string product_name { get; set; }
        public virtual Guid product_owner_id { get; set; }
        public virtual string product_description { get; set; }
        
        //<IndexOnly>
        
        public int version_count { get; set; }
        
        //</IndexOnly>
	}
}

