//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Stencil.SDK.Models
{
    public partial class ProductVersion : SDKModel
    {	
        public ProductVersion()
        {
				
        }
    
        public virtual Guid product_version_id { get; set; }
        public virtual Guid product_id { get; set; }
        public virtual string version { get; set; }
        public virtual DateTime? release_date_utc { get; set; }
        public virtual DateTime? end_of_life_date_utc { get; set; }
        
        //<IndexOnly>
        
        public string product_name { get; set; }
        
        //</IndexOnly>
	}
}

