//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Stencil.SDK.Models
{
    public partial class Ticket : SDKModel
    {	
        public Ticket()
        {
				
        }
    
        public virtual Guid ticket_id { get; set; }
        public virtual Guid reported_by_id { get; set; }
        public virtual Guid? assigned_to_id { get; set; }
        public virtual TicketType ticket_type { get; set; }
        public virtual TicketStatus ticket_status { get; set; }
        public virtual DateTime opened_on_utc { get; set; }
        public virtual DateTime? closed_on_utc { get; set; }
        public virtual string ticket_title { get; set; }
        public virtual string ticket_description { get; set; }
        
	}
}

