//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Stencil.SDK.Models
{
    public partial class TicketComment : SDKModel
    {	
        public TicketComment()
        {
				
        }
    
        public virtual Guid ticket_comment_id { get; set; }
        public virtual Guid ticket_id { get; set; }
        public virtual Guid commenter_id { get; set; }
        public virtual DateTime commented_on_utc { get; set; }
        public virtual string ticket_comment { get; set; }
        
        //<IndexOnly>
        
        public string account_name { get; set; }
        public string account_email { get; set; }
        
        //</IndexOnly>
	}
}

