//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Codeable.Foundation.Common;
using Codeable.Foundation.Common.Aspect;
using EntityFramework.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Stencil.Domain;
using Stencil.Data.Sql;
using Stencil.Primary.Synchronization;

namespace Stencil.Primary.Business.Direct.Implementation
{
    // WARNING: THIS FILE IS GENERATED
    public partial class TicketBusiness : BusinessBase, ITicketBusiness
    {
        public TicketBusiness(IFoundation foundation)
            : base(foundation, "Ticket")
        {
        }
        
        protected ITicketSynchronizer Synchronizer
        {
            get
            {
                return this.IFoundation.Resolve<ITicketSynchronizer>();
            }
        }

        public Ticket Insert(Ticket insertTicket)
        {
            return base.ExecuteFunction("Insert", delegate()
            {
                using (var db = base.CreateSQLContext())
                {
                    

                    this.PreProcess(insertTicket, true);
                    var interception = this.Intercept(insertTicket, true);
                    if(interception.Intercepted)
                    {
                        return interception.ReturnEntity;
                    }
                    
                    if (insertTicket.ticket_id == Guid.Empty)
                    {
                        insertTicket.ticket_id = Guid.NewGuid();
                    }
                    insertTicket.created_utc = DateTime.UtcNow;
                    insertTicket.updated_utc = insertTicket.created_utc;

                    dbTicket dbModel = insertTicket.ToDbModel();
                    
                    dbModel.InvalidateSync(this.DefaultAgent, "insert");

                    db.dbTickets.Add(dbModel);

                    db.SaveChanges();
                    
                    this.AfterInsertPersisted(db, dbModel);
                    
                    this.Synchronizer.SynchronizeItem(dbModel.ticket_id, Availability.Retrievable);
                    this.AfterInsertIndexed(db, dbModel);
                    
                    this.DependencyCoordinator.TicketInvalidated(Dependency.None, dbModel.ticket_id);
                }
                return this.GetById(insertTicket.ticket_id);
            });
        }
        public Ticket Update(Ticket updateTicket)
        {
            return base.ExecuteFunction("Update", delegate()
            {
                using (var db = base.CreateSQLContext())
                {
                    this.PreProcess(updateTicket, false);
                    var interception = this.Intercept(updateTicket, false);
                    if(interception.Intercepted)
                    {
                        return interception.ReturnEntity;
                    }
                    
                    updateTicket.updated_utc = DateTime.UtcNow;
                    
                    dbTicket found = (from n in db.dbTickets
                                    where n.ticket_id == updateTicket.ticket_id
                                    select n).FirstOrDefault();

                    if (found != null)
                    {
                        Ticket previous = found.ToDomainModel();
                        
                        found = updateTicket.ToDbModel(found);

                        this.BeforeUpdatePersisted(found, previous);

                        found.InvalidateSync(this.DefaultAgent, "updated");
                        db.SaveChanges();
                        
                        this.AfterUpdatePersisted(db, found, previous);
                        
                        this.Synchronizer.SynchronizeItem(found.ticket_id, Availability.Retrievable);
                        this.AfterUpdateIndexed(db, found);
                        
                        this.DependencyCoordinator.TicketInvalidated(Dependency.None, found.ticket_id);
                    
                    }
                    
                    return this.GetById(updateTicket.ticket_id);
                }
            });
        }
        public void Delete(Guid ticket_id)
        {
            base.ExecuteMethod("Delete", delegate()
            {
                
                using (var db = base.CreateSQLContext())
                {
                    dbTicket found = (from a in db.dbTickets
                                    where a.ticket_id == ticket_id
                                    select a).FirstOrDefault();

                    if (found != null)
                    {
                        
                        found.deleted_utc = DateTime.UtcNow;
                        found.InvalidateSync(this.DefaultAgent, "deleted");
                        db.SaveChanges();
                        
                        this.AfterDeletePersisted(db, found);
                        
                        this.Synchronizer.SynchronizeItem(found.ticket_id, Availability.Retrievable);
                        
                        this.DependencyCoordinator.TicketInvalidated(Dependency.None, found.ticket_id);
                    }
                }
            });
        }
        public void SynchronizationUpdate(Guid ticket_id, bool success, DateTime sync_date_utc, string sync_log)
        {
            base.ExecuteMethod("SynchronizationUpdate", delegate ()
            {
                using (var db = base.CreateSQLContext())
                {
                    db.spTicket_SyncUpdate(ticket_id, success, sync_date_utc, sync_log);
                }
            });
        }
        public List<Guid?> SynchronizationGetInvalid(int retryPriorityThreshold, string sync_agent)
        {
            return base.ExecuteFunction("SynchronizationGetInvalid", delegate ()
            {
                using (var db = base.CreateSQLContext())
                {
                    return db.spTicket_SyncGetInvalid(retryPriorityThreshold, sync_agent).ToList();
                }
            });
        }
        public void SynchronizationHydrateUpdate(Guid ticket_id, bool success, DateTime sync_date_utc, string sync_log)
        {
            base.ExecuteMethod("SynchronizationHydrateUpdate", delegate ()
            {
                using (var db = base.CreateSQLContext())
                {
                    db.spTicket_HydrateSyncUpdate(ticket_id, success, sync_date_utc, sync_log);
                }
            });
        }
        public List<Guid?> SynchronizationHydrateGetInvalid(int retryPriorityThreshold, string sync_agent)
        {
            return base.ExecuteFunction("SynchronizationHydrateGetInvalid", delegate ()
            {
                using (var db = base.CreateSQLContext())
                {
                    return db.spTicket_HydrateSyncGetInvalid(retryPriorityThreshold, sync_agent).ToList();
                }
            });
        }
        
        public Ticket GetById(Guid ticket_id)
        {
            return base.ExecuteFunction("GetById", delegate()
            {
                using (var db = this.CreateSQLContext())
                {
                    dbTicket result = (from n in db.dbTickets
                                     where (n.ticket_id == ticket_id)
                                     select n).FirstOrDefault();
                    return result.ToDomainModel();
                }
            });
        }
        public List<Ticket> GetByReportedByID(Guid account_id)
        {
            return base.ExecuteFunction("GetByReportedByID", delegate()
            {
                using (var db = this.CreateSQLContext())
                {
                    var result = (from n in db.dbTickets
                                     where (n.reported_by_id == account_id)
                                     select n);
                    return result.ToDomainModel();
                }
            });
        }
        
        public List<Ticket> GetByAssignedToID(Guid account_id)
        {
            return base.ExecuteFunction("GetByAssignedToID", delegate()
            {
                using (var db = this.CreateSQLContext())
                {
                    var result = (from n in db.dbTickets
                                     where (n.assigned_to_id == account_id)
                                     select n);
                    return result.ToDomainModel();
                }
            });
        }
        
        
        public void Invalidate(Guid ticket_id, string reason)
        {
            base.ExecuteMethod("Invalidate", delegate ()
            {
                using (var db = base.CreateSQLContext())
                {
                    db.dbTickets
                        .Where(x => x.ticket_id == ticket_id)
                        .Update(x => new dbTicket() {
                            sync_success_utc = null,
                            sync_hydrate_utc = null,
                            sync_invalid_utc = DateTime.UtcNow,
                            sync_log = reason
                        });
                }
            });
        }
        public List<Ticket> Find(int skip, int take, string keyword = "", string order_by = "", bool descending = false)
        {
            return base.ExecuteFunction("Find", delegate()
            {
                using (var db = this.CreateSQLContext())
                {
                    if(string.IsNullOrEmpty(keyword))
                    { 
                        keyword = ""; 
                    }

                    var data = (from p in db.dbTickets
                                where (keyword == "" 
                                    || p.ticket_title.Contains(keyword)
                                
                                    || p.ticket_description.Contains(keyword)
                                )
                                select p);

                    List<dbTicket> result = new List<dbTicket>();

                    switch (order_by)
                    {
                        case "opened_on_utc":
                            if (!descending)
                            {
                                result = data.OrderBy(s => s.opened_on_utc).Skip(skip).Take(take).ToList();
                            }
                            else
                            {
                                result = data.OrderByDescending(s => s.opened_on_utc).Skip(skip).Take(take).ToList();
                            }
                            break;
                        
                        case "closed_on_utc":
                            if (!descending)
                            {
                                result = data.OrderBy(s => s.closed_on_utc).Skip(skip).Take(take).ToList();
                            }
                            else
                            {
                                result = data.OrderByDescending(s => s.closed_on_utc).Skip(skip).Take(take).ToList();
                            }
                            break;
                        
                        case "ticket_title":
                            if (!descending)
                            {
                                result = data.OrderBy(s => s.ticket_title).Skip(skip).Take(take).ToList();
                            }
                            else
                            {
                                result = data.OrderByDescending(s => s.ticket_title).Skip(skip).Take(take).ToList();
                            }
                            break;
                        
                        default:
                            result = data.OrderBy(s => s.ticket_id).Skip(skip).Take(take).ToList();
                            break;
                    }
                    return result.ToDomainModel();
                }
            });
        }
        


        
        
        public InterceptArgs<Ticket> Intercept(Ticket ticket, bool forInsert)
        {
            InterceptArgs<Ticket> args = new InterceptArgs<Ticket>()
            {
                ForInsert = forInsert,
                ReturnEntity = ticket
            };
            this.PerformIntercept(args);
            return args;
        }

        partial void PerformIntercept(InterceptArgs<Ticket> args);
        partial void PreProcess(Ticket ticket, bool forInsert);
        partial void AfterInsertPersisted(StencilContext db, dbTicket ticket);
        partial void BeforeUpdatePersisted(dbTicket ticket, Ticket previous);
        partial void AfterUpdatePersisted(StencilContext db, dbTicket ticket, Ticket previous);
        partial void AfterDeletePersisted(StencilContext db, dbTicket ticket);
        partial void AfterUpdateIndexed(StencilContext db, dbTicket ticket);
        partial void AfterInsertIndexed(StencilContext db, dbTicket ticket);
    }
}

