//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Codeable.Foundation.Common;
using Stencil.SDK;
using sdk = Stencil.SDK.Models;
using Stencil.SDK.Models;
using Nest;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stencil.Primary.Business.Index.Implementation
{
    public partial class AffectedProductIndex : IndexerBase<sdk.AffectedProduct>, IAffectedProductIndex
    {
        public AffectedProductIndex(IFoundation foundation)
            : base(foundation, "AffectedProductIndex", DocumentNames.AffectedProduct)
        {

        }
        protected override string GetModelId(sdk.AffectedProduct model)
        {
            return model.affected_product_id.ToString();
        }
        public ListResult<sdk.AffectedProduct> GetByTicketID(Guid ticket_id, int skip, int take, string order_by = "", bool descending = false)
        {
            return base.ExecuteFunction("GetByTicketID", delegate ()
            {
                QueryContainer query = Query<sdk.AffectedProduct>.Term(w => w.ticket_id, ticket_id);

                

                int takePlus = take;
                if(take != int.MaxValue)
                {
                    takePlus++; // for stepping
                }
                
                List<SortFieldDescriptor<sdk.AffectedProduct>> sortFields = new List<SortFieldDescriptor<sdk.AffectedProduct>>();
                if(!string.IsNullOrEmpty(order_by))
                {
                    SortFieldDescriptor<sdk.AffectedProduct> item = new SortFieldDescriptor<sdk.AffectedProduct>()
                        .Field(order_by)
                        .Order(descending ? SortOrder.Descending : SortOrder.Ascending);
                        
                    sortFields.Add(item);
                }
                SortFieldDescriptor<sdk.AffectedProduct> defaultSort = new SortFieldDescriptor<sdk.AffectedProduct>()
                    .Field(r => r.affected_product_id)
                    .Ascending();
                
                sortFields.Add(defaultSort);
                
                ElasticClient client = this.ClientFactory.CreateClient();
                ISearchResponse<sdk.AffectedProduct> searchResponse = client.Search<sdk.AffectedProduct>(s => s
                    .Query(q => query)
                    .Skip(skip)
                    .Take(takePlus)
                    .Sort(sr => sr.Multi(sortFields))
                    .Type(this.DocumentType));

                ListResult<sdk.AffectedProduct> result = searchResponse.Documents.ToSteppedListResult(skip, take, searchResponse.GetTotalHit());
                
                return result;
            });
        }
        public ListResult<sdk.AffectedProduct> GetByProductID(Guid product_id, int skip, int take, string order_by = "", bool descending = false)
        {
            return base.ExecuteFunction("GetByProductID", delegate ()
            {
                QueryContainer query = Query<sdk.AffectedProduct>.Term(w => w.product_id, product_id);

                

                int takePlus = take;
                if(take != int.MaxValue)
                {
                    takePlus++; // for stepping
                }
                
                List<SortFieldDescriptor<sdk.AffectedProduct>> sortFields = new List<SortFieldDescriptor<sdk.AffectedProduct>>();
                if(!string.IsNullOrEmpty(order_by))
                {
                    SortFieldDescriptor<sdk.AffectedProduct> item = new SortFieldDescriptor<sdk.AffectedProduct>()
                        .Field(order_by)
                        .Order(descending ? SortOrder.Descending : SortOrder.Ascending);
                        
                    sortFields.Add(item);
                }
                SortFieldDescriptor<sdk.AffectedProduct> defaultSort = new SortFieldDescriptor<sdk.AffectedProduct>()
                    .Field(r => r.affected_product_id)
                    .Ascending();
                
                sortFields.Add(defaultSort);
                
                ElasticClient client = this.ClientFactory.CreateClient();
                ISearchResponse<sdk.AffectedProduct> searchResponse = client.Search<sdk.AffectedProduct>(s => s
                    .Query(q => query)
                    .Skip(skip)
                    .Take(takePlus)
                    .Sort(sr => sr.Multi(sortFields))
                    .Type(this.DocumentType));

                ListResult<sdk.AffectedProduct> result = searchResponse.Documents.ToSteppedListResult(skip, take, searchResponse.GetTotalHit());
                
                return result;
            });
        }
        

    }
}
