//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Codeable.Foundation.Common;
using Stencil.SDK;
using sdk = Stencil.SDK.Models;
using Stencil.SDK.Models;
using Nest;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stencil.Primary.Business.Index.Implementation
{
    public partial class ProductVersionPlatformIndex : IndexerBase<sdk.ProductVersionPlatform>, IProductVersionPlatformIndex
    {
        public ProductVersionPlatformIndex(IFoundation foundation)
            : base(foundation, "ProductVersionPlatformIndex", DocumentNames.ProductVersionPlatform)
        {

        }
        protected override string GetModelId(sdk.ProductVersionPlatform model)
        {
            return model.product_version_platform_id.ToString();
        }
        public ListResult<sdk.ProductVersionPlatform> GetByProductVerisonID(Guid product_version_id, int skip, int take, string order_by = "", bool descending = false)
        {
            return base.ExecuteFunction("GetByProductVerisonID", delegate ()
            {
                QueryContainer query = Query<sdk.ProductVersionPlatform>.Term(w => w.product_version_id, product_version_id);

                

                int takePlus = take;
                if(take != int.MaxValue)
                {
                    takePlus++; // for stepping
                }
                
                List<SortFieldDescriptor<sdk.ProductVersionPlatform>> sortFields = new List<SortFieldDescriptor<sdk.ProductVersionPlatform>>();
                if(!string.IsNullOrEmpty(order_by))
                {
                    SortFieldDescriptor<sdk.ProductVersionPlatform> item = new SortFieldDescriptor<sdk.ProductVersionPlatform>()
                        .Field(order_by)
                        .Order(descending ? SortOrder.Descending : SortOrder.Ascending);
                        
                    sortFields.Add(item);
                }
                SortFieldDescriptor<sdk.ProductVersionPlatform> defaultSort = new SortFieldDescriptor<sdk.ProductVersionPlatform>()
                    .Field(r => r.product_version_platform_id)
                    .Ascending();
                
                sortFields.Add(defaultSort);
                
                ElasticClient client = this.ClientFactory.CreateClient();
                ISearchResponse<sdk.ProductVersionPlatform> searchResponse = client.Search<sdk.ProductVersionPlatform>(s => s
                    .Query(q => query)
                    .Skip(skip)
                    .Take(takePlus)
                    .Sort(sr => sr.Multi(sortFields))
                    .Type(this.DocumentType));

                ListResult<sdk.ProductVersionPlatform> result = searchResponse.Documents.ToSteppedListResult(skip, take, searchResponse.GetTotalHit());
                
                return result;
            });
        }
        public ListResult<sdk.ProductVersionPlatform> GetByPlatformID(Guid platform_id, int skip, int take, string order_by = "", bool descending = false)
        {
            return base.ExecuteFunction("GetByPlatformID", delegate ()
            {
                QueryContainer query = Query<sdk.ProductVersionPlatform>.Term(w => w.platform_id, platform_id);

                

                int takePlus = take;
                if(take != int.MaxValue)
                {
                    takePlus++; // for stepping
                }
                
                List<SortFieldDescriptor<sdk.ProductVersionPlatform>> sortFields = new List<SortFieldDescriptor<sdk.ProductVersionPlatform>>();
                if(!string.IsNullOrEmpty(order_by))
                {
                    SortFieldDescriptor<sdk.ProductVersionPlatform> item = new SortFieldDescriptor<sdk.ProductVersionPlatform>()
                        .Field(order_by)
                        .Order(descending ? SortOrder.Descending : SortOrder.Ascending);
                        
                    sortFields.Add(item);
                }
                SortFieldDescriptor<sdk.ProductVersionPlatform> defaultSort = new SortFieldDescriptor<sdk.ProductVersionPlatform>()
                    .Field(r => r.product_version_platform_id)
                    .Ascending();
                
                sortFields.Add(defaultSort);
                
                ElasticClient client = this.ClientFactory.CreateClient();
                ISearchResponse<sdk.ProductVersionPlatform> searchResponse = client.Search<sdk.ProductVersionPlatform>(s => s
                    .Query(q => query)
                    .Skip(skip)
                    .Take(takePlus)
                    .Sort(sr => sr.Multi(sortFields))
                    .Type(this.DocumentType));

                ListResult<sdk.ProductVersionPlatform> result = searchResponse.Documents.ToSteppedListResult(skip, take, searchResponse.GetTotalHit());
                
                return result;
            });
        }
        

    }
}
