//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Codeable.Foundation.Common;
using Stencil.SDK;
using sdk = Stencil.SDK.Models;
using Stencil.SDK.Models;
using Nest;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stencil.Primary.Business.Index.Implementation
{
    public partial class ProductVersionIndex : IndexerBase<sdk.ProductVersion>, IProductVersionIndex
    {
        public ProductVersionIndex(IFoundation foundation)
            : base(foundation, "ProductVersionIndex", DocumentNames.ProductVersion)
        {

        }
        protected override string GetModelId(sdk.ProductVersion model)
        {
            return model.product_version_id.ToString();
        }
        public ListResult<sdk.ProductVersion> GetByProductID(Guid product_id, int skip, int take, string order_by = "", bool descending = false)
        {
            return base.ExecuteFunction("GetByProductID", delegate ()
            {
                QueryContainer query = Query<sdk.ProductVersion>.Term(w => w.product_id, product_id);

                

                int takePlus = take;
                if(take != int.MaxValue)
                {
                    takePlus++; // for stepping
                }
                
                List<SortFieldDescriptor<sdk.ProductVersion>> sortFields = new List<SortFieldDescriptor<sdk.ProductVersion>>();
                if(!string.IsNullOrEmpty(order_by))
                {
                    SortFieldDescriptor<sdk.ProductVersion> item = new SortFieldDescriptor<sdk.ProductVersion>()
                        .Field(order_by)
                        .Order(descending ? SortOrder.Descending : SortOrder.Ascending);
                        
                    sortFields.Add(item);
                }
                SortFieldDescriptor<sdk.ProductVersion> defaultSort = new SortFieldDescriptor<sdk.ProductVersion>()
                    .Field(r => r.product_version_id)
                    .Ascending();
                
                sortFields.Add(defaultSort);
                
                ElasticClient client = this.ClientFactory.CreateClient();
                ISearchResponse<sdk.ProductVersion> searchResponse = client.Search<sdk.ProductVersion>(s => s
                    .Query(q => query)
                    .Skip(skip)
                    .Take(takePlus)
                    .Sort(sr => sr.Multi(sortFields))
                    .Type(this.DocumentType));

                ListResult<sdk.ProductVersion> result = searchResponse.Documents.ToSteppedListResult(skip, take, searchResponse.GetTotalHit());
                
                return result;
            });
        }
        
        public ListResult<sdk.ProductVersion> Find(int skip, int take, string keyword = "", string order_by = "", bool descending = false, Guid? product_id = null)
        {
            return base.ExecuteFunction("Find", delegate ()
            {
                int takePlus = take;
                if(take != int.MaxValue)
                {
                    takePlus++; // for stepping
                }
                
                QueryContainer query = Query<sdk.ProductVersion>
                    .MultiMatch(m => m
                        .Query(keyword)
                        .Type(TextQueryType.PhrasePrefix)
                        .Fields(mf => mf
                                .Field(f => f.version)
                ));
                                
                if(product_id.HasValue)
                {
                    query &= Query<sdk.ProductVersion>.Term(f => f.product_id, product_id.Value);
                }
                
                
                SortOrder sortOrder = SortOrder.Ascending;
                if (descending)
                {
                    sortOrder = SortOrder.Descending;
                }
                if (string.IsNullOrEmpty(order_by))
                {
                    order_by = "";
                }

                ElasticClient client = this.ClientFactory.CreateClient();
                ISearchResponse<sdk.ProductVersion> searchResponse = client.Search<sdk.ProductVersion>(s => s
                    .Query(q => query)
                    .Skip(skip)
                    .Take(takePlus)
                    .Sort(r => r.Field(order_by, sortOrder))
                    .Type(this.DocumentType));
                
                ListResult<sdk.ProductVersion> result = searchResponse.Documents.ToSteppedListResult(skip, take, searchResponse.GetTotalHit());
                
                return result;
            });
        }
        

    }
}
