//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Codeable.Foundation.Common;
using Stencil.SDK;
using sdk = Stencil.SDK.Models;
using Stencil.SDK.Models;
using Nest;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stencil.Primary.Business.Index.Implementation
{
    public partial class TicketCommentIndex : IndexerBase<sdk.TicketComment>, ITicketCommentIndex
    {
        public TicketCommentIndex(IFoundation foundation)
            : base(foundation, "TicketCommentIndex", DocumentNames.TicketComment)
        {

        }
        protected override string GetModelId(sdk.TicketComment model)
        {
            return model.ticket_comment_id.ToString();
        }
        public ListResult<sdk.TicketComment> GetByTicketID(Guid ticket_id, int skip, int take, string order_by = "", bool descending = false)
        {
            return base.ExecuteFunction("GetByTicketID", delegate ()
            {
                QueryContainer query = Query<sdk.TicketComment>.Term(w => w.ticket_id, ticket_id);

                

                int takePlus = take;
                if(take != int.MaxValue)
                {
                    takePlus++; // for stepping
                }
                
                List<SortFieldDescriptor<sdk.TicketComment>> sortFields = new List<SortFieldDescriptor<sdk.TicketComment>>();
                if(!string.IsNullOrEmpty(order_by))
                {
                    SortFieldDescriptor<sdk.TicketComment> item = new SortFieldDescriptor<sdk.TicketComment>()
                        .Field(order_by)
                        .Order(descending ? SortOrder.Descending : SortOrder.Ascending);
                        
                    sortFields.Add(item);
                }
                SortFieldDescriptor<sdk.TicketComment> defaultSort = new SortFieldDescriptor<sdk.TicketComment>()
                    .Field(r => r.ticket_comment_id)
                    .Ascending();
                
                sortFields.Add(defaultSort);
                
                ElasticClient client = this.ClientFactory.CreateClient();
                ISearchResponse<sdk.TicketComment> searchResponse = client.Search<sdk.TicketComment>(s => s
                    .Query(q => query)
                    .Skip(skip)
                    .Take(takePlus)
                    .Sort(sr => sr.Multi(sortFields))
                    .Type(this.DocumentType));

                ListResult<sdk.TicketComment> result = searchResponse.Documents.ToSteppedListResult(skip, take, searchResponse.GetTotalHit());
                
                return result;
            });
        }
        public ListResult<sdk.TicketComment> GetByCommenterID(Guid account_id, int skip, int take, string order_by = "", bool descending = false)
        {
            return base.ExecuteFunction("GetByCommenterID", delegate ()
            {
                QueryContainer query = Query<sdk.TicketComment>.Term(w => w.commenter_id, account_id);

                

                int takePlus = take;
                if(take != int.MaxValue)
                {
                    takePlus++; // for stepping
                }
                
                List<SortFieldDescriptor<sdk.TicketComment>> sortFields = new List<SortFieldDescriptor<sdk.TicketComment>>();
                if(!string.IsNullOrEmpty(order_by))
                {
                    SortFieldDescriptor<sdk.TicketComment> item = new SortFieldDescriptor<sdk.TicketComment>()
                        .Field(order_by)
                        .Order(descending ? SortOrder.Descending : SortOrder.Ascending);
                        
                    sortFields.Add(item);
                }
                SortFieldDescriptor<sdk.TicketComment> defaultSort = new SortFieldDescriptor<sdk.TicketComment>()
                    .Field(r => r.ticket_comment_id)
                    .Ascending();
                
                sortFields.Add(defaultSort);
                
                ElasticClient client = this.ClientFactory.CreateClient();
                ISearchResponse<sdk.TicketComment> searchResponse = client.Search<sdk.TicketComment>(s => s
                    .Query(q => query)
                    .Skip(skip)
                    .Take(takePlus)
                    .Sort(sr => sr.Multi(sortFields))
                    .Type(this.DocumentType));

                ListResult<sdk.TicketComment> result = searchResponse.Documents.ToSteppedListResult(skip, take, searchResponse.GetTotalHit());
                
                return result;
            });
        }
        

    }
}
