//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stencil.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbCommit
    {
        public string commit_ref { get; set; }
        public string commit_author_name { get; set; }
        public string commit_author_email { get; set; }
        public Nullable<System.DateTimeOffset> commit_message_decoded_utc { get; set; }
        public string commit_message { get; set; }
        public System.DateTimeOffset created_utc { get; set; }
        public System.DateTimeOffset updated_utc { get; set; }
        public System.Guid commit_id { get; set; }
    }
}
