//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stencil.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbTicket
    {
        public System.Guid ticket_id { get; set; }
        public System.Guid reported_by_id { get; set; }
        public Nullable<System.Guid> assigned_to_id { get; set; }
        public int ticket_type { get; set; }
        public int ticket_status { get; set; }
        public System.DateTimeOffset opened_on_utc { get; set; }
        public Nullable<System.DateTimeOffset> closed_on_utc { get; set; }
        public string ticket_title { get; set; }
        public string ticket_description { get; set; }
        public System.DateTimeOffset created_utc { get; set; }
        public System.DateTimeOffset updated_utc { get; set; }
        public Nullable<System.DateTimeOffset> deleted_utc { get; set; }
        public Nullable<System.DateTimeOffset> sync_hydrate_utc { get; set; }
        public Nullable<System.DateTimeOffset> sync_success_utc { get; set; }
        public Nullable<System.DateTimeOffset> sync_invalid_utc { get; set; }
        public Nullable<System.DateTimeOffset> sync_attempt_utc { get; set; }
        public string sync_agent { get; set; }
        public string sync_log { get; set; }
    
        public virtual dbAccount AssignedTo { get; set; }
        public virtual dbAccount ReportedBy { get; set; }
    }
}
