//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Stencil.SDK.Endpoints;
using System;
using System.Collections.Generic;
using System.Text;

namespace Stencil.SDK
{
    public partial class StencilSDK
    {
        // members for web ease
        public GlobalSettingEndpoint GlobalSetting;
        public AccountEndpoint Account;
        public ProductEndpoint Product;
        public PlatformEndpoint Platform;
        public ProductVersionEndpoint ProductVersion;
        public ProductVersionPlatformEndpoint ProductVersionPlatform;
        public TicketEndpoint Ticket;
        public AffectedProductEndpoint AffectedProduct;
        public AssetEndpoint Asset;
        

        protected virtual void ConstructCoreEndpoints()
        {
            this.GlobalSetting = new GlobalSettingEndpoint(this);
            this.Account = new AccountEndpoint(this);
            this.Product = new ProductEndpoint(this);
            this.Platform = new PlatformEndpoint(this);
            this.ProductVersion = new ProductVersionEndpoint(this);
            this.ProductVersionPlatform = new ProductVersionPlatformEndpoint(this);
            this.Ticket = new TicketEndpoint(this);
            this.AffectedProduct = new AffectedProductEndpoint(this);
            this.Asset = new AssetEndpoint(this);
            
        }   
    }
}

