//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Stencil.Domain;

namespace Stencil.Primary.Business.Direct
{
    // WARNING: THIS FILE IS GENERATED
    public partial interface IAffectedProductBusiness
    {
        AffectedProduct GetById(Guid affected_product_id);
        
        List<AffectedProduct> GetByTicketID(Guid ticket_id);
        
        List<AffectedProduct> GetByProductID(Guid product_id);
        AffectedProduct Insert(AffectedProduct insertAffectedProduct);
        AffectedProduct Update(AffectedProduct updateAffectedProduct);
        
        void Delete(Guid affected_product_id);
        void SynchronizationUpdate(Guid affected_product_id, bool success, DateTime sync_date_utc, string sync_log);
        List<Guid?> SynchronizationGetInvalid(int retryPriorityThreshold, string sync_agent);
        void SynchronizationHydrateUpdate(Guid affected_product_id, bool success, DateTime sync_date_utc, string sync_log);
        List<Guid?> SynchronizationHydrateGetInvalid(int retryPriorityThreshold, string sync_agent);
        void Invalidate(Guid affected_product_id, string reason);
        
    }
}

