//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Stencil.Domain;

namespace Stencil.Primary.Business.Direct
{
    // WARNING: THIS FILE IS GENERATED
    public partial interface IProductVersionPlatformBusiness
    {
        ProductVersionPlatform GetById(Guid product_version_platform_id);
        
        List<ProductVersionPlatform> GetByProductVerisonID(Guid product_version_id);
        void InvalidateForProductVerisonID(Guid product_version_id, string reason);
        List<ProductVersionPlatform> GetByPlatformID(Guid platform_id);
        void InvalidateForPlatformID(Guid platform_id, string reason);ProductVersionPlatform Insert(ProductVersionPlatform insertProductVersionPlatform);
        ProductVersionPlatform Update(ProductVersionPlatform updateProductVersionPlatform);
        
        void Delete(Guid product_version_platform_id);
        void SynchronizationUpdate(Guid product_version_platform_id, bool success, DateTime sync_date_utc, string sync_log);
        List<Guid?> SynchronizationGetInvalid(int retryPriorityThreshold, string sync_agent);
        void SynchronizationHydrateUpdate(Guid product_version_platform_id, bool success, DateTime sync_date_utc, string sync_log);
        List<Guid?> SynchronizationHydrateGetInvalid(int retryPriorityThreshold, string sync_agent);
        void Invalidate(Guid product_version_platform_id, string reason);
        
    }
}

