//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Stencil.Domain;

namespace Stencil.Primary.Business.Direct
{
    // WARNING: THIS FILE IS GENERATED
    public partial interface ITicketBusiness
    {
        Ticket GetById(Guid ticket_id);
        List<Ticket> Find(int skip, int take, string keyword = "", string order_by = "", bool descending = false);
        
        List<Ticket> GetByReportedByID(Guid account_id);
        
        List<Ticket> GetByAssignedToID(Guid account_id);
        Ticket Insert(Ticket insertTicket);
        Ticket Update(Ticket updateTicket);
        
        void Delete(Guid ticket_id);
        void SynchronizationUpdate(Guid ticket_id, bool success, DateTime sync_date_utc, string sync_log);
        List<Guid?> SynchronizationGetInvalid(int retryPriorityThreshold, string sync_agent);
        void SynchronizationHydrateUpdate(Guid ticket_id, bool success, DateTime sync_date_utc, string sync_log);
        List<Guid?> SynchronizationHydrateGetInvalid(int retryPriorityThreshold, string sync_agent);
        void Invalidate(Guid ticket_id, string reason);
        
    }
}

