//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Stencil.Domain;

namespace Stencil.Primary.Business.Direct
{
    // WARNING: THIS FILE IS GENERATED
    public partial interface ITicketCommentBusiness
    {
        TicketComment GetById(Guid ticket_comment_id);
        
        List<TicketComment> GetByTicketID(Guid ticket_id);
        
        List<TicketComment> GetByCommenterID(Guid account_id);
        void InvalidateForCommenterID(Guid account_id, string reason);TicketComment Insert(TicketComment insertTicketComment);
        TicketComment Update(TicketComment updateTicketComment);
        
        void Delete(Guid ticket_comment_id);
        void SynchronizationUpdate(Guid ticket_comment_id, bool success, DateTime sync_date_utc, string sync_log);
        List<Guid?> SynchronizationGetInvalid(int retryPriorityThreshold, string sync_agent);
        void SynchronizationHydrateUpdate(Guid ticket_comment_id, bool success, DateTime sync_date_utc, string sync_log);
        List<Guid?> SynchronizationHydrateGetInvalid(int retryPriorityThreshold, string sync_agent);
        void Invalidate(Guid ticket_comment_id, string reason);
        
    }
}

