//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Codeable.Foundation.Common;
using Codeable.Foundation.Core;
using System;
using System.Web.Http;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using sdk = Stencil.SDK.Models;
using dm = Stencil.Domain;
using Stencil.Primary;
using Stencil.SDK;
using Stencil.Web.Controllers;
using Stencil.Web.Security;

namespace Stencil.Plugins.RestAPI.Controllers
{
    [ApiKeyHttpAuthorize]
    [RoutePrefix("api/affectedproducts")]
    public partial class AffectedProductController : HealthRestApiController
    {
        public AffectedProductController(IFoundation foundation)
            : base(foundation, "AffectedProduct")
        {
        }

        [HttpGet]
        [Route("{affected_product_id}")]
        public object GetById(Guid affected_product_id)
        {
            return base.ExecuteFunction<object>("GetById", delegate()
            {
                this.BeforeGet();

                sdk.AffectedProduct result = this.API.Index.AffectedProducts.GetById(affected_product_id);
                if (result == null)
                {
                    return Http404("AffectedProduct");
                }

                this.AfterGet(result);

                

                return base.Http200(new ItemResult<sdk.AffectedProduct>()
                {
                    success = true, 
                    item = result
                });
            });
        }

        partial void BeforeGet();
        partial void AfterGet(sdk.AffectedProduct result);
        partial void AfterGet(ListResult<sdk.AffectedProduct> result);
        
        
        [HttpGet]
        [Route("by_ticketid/{ticket_id}")]
        public object GetByTicketID(Guid ticket_id, int skip = 0, int take = 10, string order_by = "", bool descending = false)
        {
            return base.ExecuteFunction<object>("GetByTicketID", delegate ()
            {
                this.BeforeGet();

                
                ListResult<sdk.AffectedProduct> result = this.API.Index.AffectedProducts.GetByTicketID(ticket_id, skip, take, order_by, descending);
                result.success = true;

                this.AfterGet(result);

                return base.Http200(result);
            });
        }
        
        [HttpGet]
        [Route("by_productid/{product_id}")]
        public object GetByProductID(Guid product_id, int skip = 0, int take = 10, string order_by = "", bool descending = false)
        {
            return base.ExecuteFunction<object>("GetByProductID", delegate ()
            {
                this.BeforeGet();

                
                ListResult<sdk.AffectedProduct> result = this.API.Index.AffectedProducts.GetByProductID(product_id, skip, take, order_by, descending);
                result.success = true;

                this.AfterGet(result);

                return base.Http200(result);
            });
        }
        
        
        
       

        [HttpPost]
        [Route("")]
        public object Create(sdk.AffectedProduct affectedproduct)
        {
            return base.ExecuteFunction<object>("Create", delegate()
            {
                this.ValidateNotNull(affectedproduct, "AffectedProduct");

                this.BeforeInsert(affectedproduct);

                dm.AffectedProduct insert = affectedproduct.ToDomainModel();
              
                insert = this.API.Direct.AffectedProducts.Insert(insert);
                
                this.AfterInsert(affectedproduct, insert);

                
                sdk.AffectedProduct result = this.API.Index.AffectedProducts.GetById(insert.affected_product_id);

                return base.Http201(new ItemResult<sdk.AffectedProduct>()
                {
                    success = true,
                    item = result
                }
                , string.Format("api/affectedproduct/{0}", affectedproduct.affected_product_id));

            });

        }

        partial void BeforeInsert(sdk.AffectedProduct affectedproduct);
        partial void AfterInsert(sdk.AffectedProduct affectedproduct, dm.AffectedProduct inserted);

        [HttpPut]
        [Route("{affected_product_id}")]
        public object Update(Guid affected_product_id, sdk.AffectedProduct affectedproduct)
        {
            return base.ExecuteFunction<object>("Update", delegate()
            {
                this.ValidateNotNull(affectedproduct, "AffectedProduct");
                this.ValidateRouteMatch(affected_product_id, affectedproduct.affected_product_id, "AffectedProduct");

                affectedproduct.affected_product_id = affected_product_id;

                this.BeforeUpdate(affectedproduct);

                dm.AffectedProduct update = affectedproduct.ToDomainModel();

                update = this.API.Direct.AffectedProducts.Update(update);

                this.AfterUpdate(affectedproduct, update);
                
                
                sdk.AffectedProduct existing = this.API.Index.AffectedProducts.GetById(update.affected_product_id);
                
                
                return base.Http200(new ItemResult<sdk.AffectedProduct>()
                {
                    success = true,
                    item = existing
                });

            });

        }

        partial void BeforeUpdate(sdk.AffectedProduct affectedproduct);
        partial void AfterUpdate(sdk.AffectedProduct affectedproduct, dm.AffectedProduct updated);

        

        [HttpDelete]
        [Route("{affected_product_id}")]
        public object Delete(Guid affected_product_id)
        {
            return base.ExecuteFunction("Delete", delegate()
            {
                dm.AffectedProduct delete = this.API.Direct.AffectedProducts.GetById(affected_product_id);
                
                this.BeforeDelete(delete);
                
                this.API.Direct.AffectedProducts.Delete(affected_product_id);

                return Http200(new ActionResult()
                {
                    success = true,
                    message = affected_product_id.ToString()
                });
            });
        }

        partial void BeforeDelete(dm.AffectedProduct delete);

    }
}

