//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Codeable.Foundation.Common;
using Codeable.Foundation.Core;
using System;
using System.Web.Http;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using sdk = Stencil.SDK.Models;
using dm = Stencil.Domain;
using Stencil.Primary;
using Stencil.SDK;
using Stencil.Web.Controllers;
using Stencil.Web.Security;

namespace Stencil.Plugins.RestAPI.Controllers
{
    [ApiKeyHttpAuthorize]
    [RoutePrefix("api/productversions")]
    public partial class ProductVersionController : HealthRestApiController
    {
        public ProductVersionController(IFoundation foundation)
            : base(foundation, "ProductVersion")
        {
        }

        [HttpGet]
        [Route("{product_version_id}")]
        public object GetById(Guid product_version_id)
        {
            return base.ExecuteFunction<object>("GetById", delegate()
            {
                this.BeforeGet();

                sdk.ProductVersion result = this.API.Index.ProductVersions.GetById(product_version_id);
                if (result == null)
                {
                    return Http404("ProductVersion");
                }

                this.AfterGet(result);

                

                return base.Http200(new ItemResult<sdk.ProductVersion>()
                {
                    success = true, 
                    item = result
                });
            });
        }

        partial void BeforeGet();
        partial void AfterGet(sdk.ProductVersion result);
        partial void AfterGet(ListResult<sdk.ProductVersion> result);
        
        
        [HttpGet]
        [Route("")]
        public object Find(int skip = 0, int take = 10, string order_by = "", bool descending = false, string keyword = "", Guid? product_id = null)
        {
            return base.ExecuteFunction<object>("Find", delegate()
            {
                this.BeforeFind();

                
                ListResult<sdk.ProductVersion> result = this.API.Index.ProductVersions.Find(skip, take, keyword, order_by, descending, product_id);
                result.success = true;

                this.AfterFind(result);

                return base.Http200(result);
            });
        }
        
        partial void BeforeFind();
        partial void AfterFind(ListResult<sdk.ProductVersion> result);
        
        
        [HttpGet]
        [Route("by_productid/{product_id}")]
        public object GetByProductID(Guid product_id, int skip = 0, int take = 10, string order_by = "", bool descending = false)
        {
            return base.ExecuteFunction<object>("GetByProductID", delegate ()
            {
                this.BeforeGet();

                
                ListResult<sdk.ProductVersion> result = this.API.Index.ProductVersions.GetByProductID(product_id, skip, take, order_by, descending);
                result.success = true;

                this.AfterGet(result);

                return base.Http200(result);
            });
        }
        
        
        
       

        [HttpPost]
        [Route("")]
        public object Create(sdk.ProductVersion productversion)
        {
            return base.ExecuteFunction<object>("Create", delegate()
            {
                this.ValidateNotNull(productversion, "ProductVersion");

                dm.ProductVersion insert = productversion.ToDomainModel();

                this.BeforeInsert(insert);
                
                insert = this.API.Direct.ProductVersions.Insert(insert);
                

                
                sdk.ProductVersion result = this.API.Index.ProductVersions.GetById(insert.product_version_id);

                return base.Http201(new ItemResult<sdk.ProductVersion>()
                {
                    success = true,
                    item = result
                }
                , string.Format("api/productversion/{0}", productversion.product_version_id));

            });

        }

        partial void BeforeInsert(dm.ProductVersion insert);

        [HttpPut]
        [Route("{product_version_id}")]
        public object Update(Guid product_version_id, sdk.ProductVersion productversion)
        {
            return base.ExecuteFunction<object>("Update", delegate()
            {
                this.ValidateNotNull(productversion, "ProductVersion");
                this.ValidateRouteMatch(product_version_id, productversion.product_version_id, "ProductVersion");

                productversion.product_version_id = product_version_id;
                dm.ProductVersion update = productversion.ToDomainModel();

                this.BeforeUpdate(update);

                update = this.API.Direct.ProductVersions.Update(update);
                
                
                sdk.ProductVersion existing = this.API.Index.ProductVersions.GetById(update.product_version_id);
                
                
                return base.Http200(new ItemResult<sdk.ProductVersion>()
                {
                    success = true,
                    item = existing
                });

            });

        }

        partial void BeforeUpdate(dm.ProductVersion insert);

        

        [HttpDelete]
        [Route("{product_version_id}")]
        public object Delete(Guid product_version_id)
        {
            return base.ExecuteFunction("Delete", delegate()
            {
                dm.ProductVersion delete = this.API.Direct.ProductVersions.GetById(product_version_id);
                
                this.BeforeDelete(delete);
                
                this.API.Direct.ProductVersions.Delete(product_version_id);

                return Http200(new ActionResult()
                {
                    success = true,
                    message = product_version_id.ToString()
                });
            });
        }

        partial void BeforeDelete(dm.ProductVersion delete);

    }
}

