//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Codeable.Foundation.Common;
using Codeable.Foundation.Core;
using System;
using System.Web.Http;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using sdk = Stencil.SDK.Models;
using dm = Stencil.Domain;
using Stencil.Primary;
using Stencil.SDK;
using Stencil.Web.Controllers;
using Stencil.Web.Security;

namespace Stencil.Plugins.RestAPI.Controllers
{
    [ApiKeyHttpAuthorize]
    [RoutePrefix("api/productversionplatforms")]
    public partial class ProductVersionPlatformController : HealthRestApiController
    {
        public ProductVersionPlatformController(IFoundation foundation)
            : base(foundation, "ProductVersionPlatform")
        {
        }

        [HttpGet]
        [Route("{product_version_platform_id}")]
        public object GetById(Guid product_version_platform_id)
        {
            return base.ExecuteFunction<object>("GetById", delegate()
            {
                this.BeforeGet();

                sdk.ProductVersionPlatform result = this.API.Index.ProductVersionPlatforms.GetById(product_version_platform_id);
                if (result == null)
                {
                    return Http404("ProductVersionPlatform");
                }

                this.AfterGet(result);

                

                return base.Http200(new ItemResult<sdk.ProductVersionPlatform>()
                {
                    success = true, 
                    item = result
                });
            });
        }

        partial void BeforeGet();
        partial void AfterGet(sdk.ProductVersionPlatform result);
        partial void AfterGet(ListResult<sdk.ProductVersionPlatform> result);
        
        
        [HttpGet]
        [Route("by_productverisonid/{product_version_id}")]
        public object GetByProductVerisonID(Guid product_version_id, int skip = 0, int take = 10, string order_by = "", bool descending = false)
        {
            return base.ExecuteFunction<object>("GetByProductVerisonID", delegate ()
            {
                this.BeforeGet();

                
                ListResult<sdk.ProductVersionPlatform> result = this.API.Index.ProductVersionPlatforms.GetByProductVerisonID(product_version_id, skip, take, order_by, descending);
                result.success = true;

                this.AfterGet(result);

                return base.Http200(result);
            });
        }
        
        [HttpGet]
        [Route("by_platformid/{platform_id}")]
        public object GetByPlatformID(Guid platform_id, int skip = 0, int take = 10, string order_by = "", bool descending = false)
        {
            return base.ExecuteFunction<object>("GetByPlatformID", delegate ()
            {
                this.BeforeGet();

                
                ListResult<sdk.ProductVersionPlatform> result = this.API.Index.ProductVersionPlatforms.GetByPlatformID(platform_id, skip, take, order_by, descending);
                result.success = true;

                this.AfterGet(result);

                return base.Http200(result);
            });
        }
        
        
        
       

        [HttpPost]
        [Route("")]
        public object Create(sdk.ProductVersionPlatform productversionplatform)
        {
            return base.ExecuteFunction<object>("Create", delegate()
            {
                this.ValidateNotNull(productversionplatform, "ProductVersionPlatform");

                this.BeforeInsert(productversionplatform);

                dm.ProductVersionPlatform insert = productversionplatform.ToDomainModel();
              
                insert = this.API.Direct.ProductVersionPlatforms.Insert(insert);
                
                this.AfterInsert(productversionplatform, insert);

                
                sdk.ProductVersionPlatform result = this.API.Index.ProductVersionPlatforms.GetById(insert.product_version_platform_id);

                return base.Http201(new ItemResult<sdk.ProductVersionPlatform>()
                {
                    success = true,
                    item = result
                }
                , string.Format("api/productversionplatform/{0}", productversionplatform.product_version_platform_id));

            });

        }

        partial void BeforeInsert(sdk.ProductVersionPlatform productversionplatform);
        partial void AfterInsert(sdk.ProductVersionPlatform productversionplatform, dm.ProductVersionPlatform inserted);

        [HttpPut]
        [Route("{product_version_platform_id}")]
        public object Update(Guid product_version_platform_id, sdk.ProductVersionPlatform productversionplatform)
        {
            return base.ExecuteFunction<object>("Update", delegate()
            {
                this.ValidateNotNull(productversionplatform, "ProductVersionPlatform");
                this.ValidateRouteMatch(product_version_platform_id, productversionplatform.product_version_platform_id, "ProductVersionPlatform");

                productversionplatform.product_version_platform_id = product_version_platform_id;

                this.BeforeUpdate(productversionplatform);

                dm.ProductVersionPlatform update = productversionplatform.ToDomainModel();

                update = this.API.Direct.ProductVersionPlatforms.Update(update);

                this.AfterUpdate(productversionplatform, update);
                
                
                sdk.ProductVersionPlatform existing = this.API.Index.ProductVersionPlatforms.GetById(update.product_version_platform_id);
                
                
                return base.Http200(new ItemResult<sdk.ProductVersionPlatform>()
                {
                    success = true,
                    item = existing
                });

            });

        }

        partial void BeforeUpdate(sdk.ProductVersionPlatform productversionplatform);
        partial void AfterUpdate(sdk.ProductVersionPlatform productversionplatform, dm.ProductVersionPlatform updated);

        

        [HttpDelete]
        [Route("{product_version_platform_id}")]
        public object Delete(Guid product_version_platform_id)
        {
            return base.ExecuteFunction("Delete", delegate()
            {
                dm.ProductVersionPlatform delete = this.API.Direct.ProductVersionPlatforms.GetById(product_version_platform_id);
                
                this.BeforeDelete(delete);
                
                this.API.Direct.ProductVersionPlatforms.Delete(product_version_platform_id);

                return Http200(new ActionResult()
                {
                    success = true,
                    message = product_version_platform_id.ToString()
                });
            });
        }

        partial void BeforeDelete(dm.ProductVersionPlatform delete);

    }
}

