//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Codeable.Foundation.Common;
using Stencil.SDK.Models;
using Stencil.SDK;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stencil.Primary.Business.Index
{
    public partial interface ITicketIndex : IIndexer<Ticket>
    {
        Ticket GetById(Guid id);
        TCustomModel GetById<TCustomModel>(Guid id)
            where TCustomModel : class;
        ListResult<Ticket> GetByReportedByID(Guid account_id, int skip, int take, string order_by = "", bool descending = false);
        ListResult<Ticket> GetByAssignedToID(Guid account_id, int skip, int take, string order_by = "", bool descending = false);
        
        ListResult<Ticket> Find(int skip, int take, string keyword = "", string order_by = "", bool descending = false, Guid? reported_by_id = null, Guid? assigned_to_id = null);
    }
}
