//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Codeable.Foundation.Core;
using System;
using System.Collections.Generic;
using System.Text;


namespace Stencil.Domain
{
    public partial class Commit : DomainModel
    {	
        public Commit()
        {
				
        }
    
        public Guid commit_id { get; set; }
        public string commit_ref { get; set; }
        public string commit_author_name { get; set; }
        public string commit_author_email { get; set; }
        public DateTime? commit_message_decoded_utc { get; set; }
        public string commit_message { get; set; }
        public DateTime created_utc { get; set; }
        public DateTime updated_utc { get; set; }
	}
}

