//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Codeable.Foundation.Core;
using System;
using System.Collections.Generic;
using System.Text;


namespace Stencil.Domain
{
    public partial class GlobalSetting : DomainModel
    {	
        public GlobalSetting()
        {
				
        }
    
        public Guid global_setting_id { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        
	}
}

