//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Codeable.Foundation.Core;
using System;
using System.Collections.Generic;
using System.Text;


namespace Stencil.Domain
{
    public partial class Ticket : DomainModel
    {	
        public Ticket()
        {
				
        }
    
        public Guid ticket_id { get; set; }
        public Guid reported_by_id { get; set; }
        public Guid? assigned_to_id { get; set; }
        public TicketType ticket_type { get; set; }
        public TicketStatus ticket_status { get; set; }
        public DateTime opened_on_utc { get; set; }
        public DateTime? closed_on_utc { get; set; }
        public string ticket_title { get; set; }
        public string ticket_description { get; set; }
        public DateTime created_utc { get; set; }
        public DateTime updated_utc { get; set; }
        public DateTime? deleted_utc { get; set; }
        public DateTime? sync_success_utc { get; set; }
        public DateTime? sync_invalid_utc { get; set; }
        public DateTime? sync_attempt_utc { get; set; }
        public string sync_agent { get; set; }
        public string sync_log { get; set; }
	}
}

