//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;

namespace Stencil.Domain
{
    public enum TicketStatus
    {
        Open = 0,
        InProgress = 1,
        Closed = 2
    }
}
