//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Stencil.Domain;
using Codeable.Foundation.Common.Aspect;
using Codeable.Foundation.Common;

namespace Stencil.Primary.Business.Integration
{
    public partial class DependencyCoordinator_Core : ChokeableClass, IDependencyCoordinator
    {
        public DependencyCoordinator_Core(IFoundation iFoundation)
            : base(iFoundation)
        {
            this.API = new StencilAPI(iFoundation);
        }
        public virtual StencilAPI API { get; set; }
        
        public virtual void GlobalSettingInvalidated(Dependency affectedDependencies, Guid global_setting_id)
        {
            base.ExecuteMethod("GlobalSettingInvalidated", delegate ()
            {
                DependencyWorker<GlobalSetting>.EnqueueRequest(this.IFoundation, affectedDependencies, global_setting_id, this.ProcessGlobalSettingInvalidation);
            });
        }
        protected virtual void ProcessGlobalSettingInvalidation(Dependency dependencies, Guid global_setting_id)
        {
            base.ExecuteMethod("ProcessGlobalSettingInvalidation", delegate ()
            {
                
            });
        }
        public virtual void AccountInvalidated(Dependency affectedDependencies, Guid account_id)
        {
            base.ExecuteMethod("AccountInvalidated", delegate ()
            {
                DependencyWorker<Account>.EnqueueRequest(this.IFoundation, affectedDependencies, account_id, this.ProcessAccountInvalidation);
            });
        }
        protected virtual void ProcessAccountInvalidation(Dependency dependencies, Guid account_id)
        {
            base.ExecuteMethod("ProcessAccountInvalidation", delegate ()
            {
                
            });
        }
        public virtual void ProductInvalidated(Dependency affectedDependencies, Guid product_id)
        {
            base.ExecuteMethod("ProductInvalidated", delegate ()
            {
                DependencyWorker<Product>.EnqueueRequest(this.IFoundation, affectedDependencies, product_id, this.ProcessProductInvalidation);
            });
        }
        protected virtual void ProcessProductInvalidation(Dependency dependencies, Guid product_id)
        {
            base.ExecuteMethod("ProcessProductInvalidation", delegate ()
            {
                
            });
        }
        public virtual void PlatformInvalidated(Dependency affectedDependencies, Guid platform_id)
        {
            base.ExecuteMethod("PlatformInvalidated", delegate ()
            {
                DependencyWorker<Platform>.EnqueueRequest(this.IFoundation, affectedDependencies, platform_id, this.ProcessPlatformInvalidation);
            });
        }
        protected virtual void ProcessPlatformInvalidation(Dependency dependencies, Guid platform_id)
        {
            base.ExecuteMethod("ProcessPlatformInvalidation", delegate ()
            {
                
                this.API.Direct.ProductVersionPlatforms.InvalidateForPlatformID(platform_id, " changed");
                
                this.API.Integration.Synchronization.AgitateSyncDaemon();
            });
        }
        public virtual void ProductVersionInvalidated(Dependency affectedDependencies, Guid product_version_id)
        {
            base.ExecuteMethod("ProductVersionInvalidated", delegate ()
            {
                DependencyWorker<ProductVersion>.EnqueueRequest(this.IFoundation, affectedDependencies, product_version_id, this.ProcessProductVersionInvalidation);
            });
        }
        protected virtual void ProcessProductVersionInvalidation(Dependency dependencies, Guid product_version_id)
        {
            base.ExecuteMethod("ProcessProductVersionInvalidation", delegate ()
            {
                
                this.API.Direct.ProductVersionPlatforms.InvalidateForProductVerisonID(product_version_id, " changed");
                ProductVersion item = this.API.Direct.ProductVersions.GetById(product_version_id);
                if (item != null)
                {
                    this.API.Direct.Products.Invalidate(item.product_id, "ProductVersion changed");
                }
                
                this.API.Integration.Synchronization.AgitateSyncDaemon();
            });
        }
        public virtual void ProductVersionPlatformInvalidated(Dependency affectedDependencies, Guid product_version_platform_id)
        {
            base.ExecuteMethod("ProductVersionPlatformInvalidated", delegate ()
            {
                DependencyWorker<ProductVersionPlatform>.EnqueueRequest(this.IFoundation, affectedDependencies, product_version_platform_id, this.ProcessProductVersionPlatformInvalidation);
            });
        }
        protected virtual void ProcessProductVersionPlatformInvalidation(Dependency dependencies, Guid product_version_platform_id)
        {
            base.ExecuteMethod("ProcessProductVersionPlatformInvalidation", delegate ()
            {
                
            });
        }
        public virtual void TicketInvalidated(Dependency affectedDependencies, Guid ticket_id)
        {
            base.ExecuteMethod("TicketInvalidated", delegate ()
            {
                DependencyWorker<Ticket>.EnqueueRequest(this.IFoundation, affectedDependencies, ticket_id, this.ProcessTicketInvalidation);
            });
        }
        protected virtual void ProcessTicketInvalidation(Dependency dependencies, Guid ticket_id)
        {
            base.ExecuteMethod("ProcessTicketInvalidation", delegate ()
            {
                
            });
        }
        public virtual void AssetInvalidated(Dependency affectedDependencies, Guid asset_id)
        {
            base.ExecuteMethod("AssetInvalidated", delegate ()
            {
                DependencyWorker<Asset>.EnqueueRequest(this.IFoundation, affectedDependencies, asset_id, this.ProcessAssetInvalidation);
            });
        }
        protected virtual void ProcessAssetInvalidation(Dependency dependencies, Guid asset_id)
        {
            base.ExecuteMethod("ProcessAssetInvalidation", delegate ()
            {
                
            });
        }
        
    }
}


